echo Revert for Light Debloater Script by invinciblevenom
echo =============================================
echo Checking connected devices
adb devices
#adb shell cmd package install-existing com.android.emergency
#adb shell cmd package install-existing com.google.android.gms.location.history
#adb shell cmd package install-existing com.samsung.android.mdx.kit
#adb shell cmd package install-existing com.samsung.android.mdx.quickboard
#adb shell cmd package install-existing com.samsung.android.samsungpositioning
#adb shell cmd package install-existing com.samsung.android.smartmirroring               #Removing it breaks Video Player
#adb shell cmd package install-existing com.sec.android.emergencymode.service
#adb shell cmd package install-existing com.sec.android.provider.emergencymode
#adb shell cmd package install-existing com.sec.unifiedwfc                               #WiFi calling app
adb shell cmd package install-existing android.autoinstalls.config.samsung
adb shell cmd package install-existing com.android.bips
adb shell cmd package install-existing com.android.bookmarkprovider
adb shell cmd package install-existing com.android.chrome
adb shell cmd package install-existing com.android.cts.ctsshim
adb shell cmd package install-existing com.android.cts.priv.ctsshim
adb shell cmd package install-existing com.android.hotwordenrollment.okgoogle
adb shell cmd package install-existing com.android.hotwordenrollment.xgoogle
adb shell cmd package install-existing com.android.htmlviewer
adb shell cmd package install-existing com.android.managedprovisioning
adb shell cmd package install-existing com.android.printspooler
adb shell cmd package install-existing com.android.providers.partnerbookmarks
adb shell cmd package install-existing com.android.stk
adb shell cmd package install-existing com.android.stk2
adb shell cmd package install-existing com.android.traceur
adb shell cmd package install-existing com.aura.oobe.samsung
adb shell cmd package install-existing com.facebook.appmanager
adb shell cmd package install-existing com.facebook.katana
adb shell cmd package install-existing com.facebook.services
adb shell cmd package install-existing com.facebook.system
adb shell cmd package install-existing com.google.android.apps.carrier.carrierwifi
adb shell cmd package install-existing com.google.android.apps.messaging
adb shell cmd package install-existing com.google.android.apps.restore
adb shell cmd package install-existing com.google.android.apps.setupwizard.searchselector
adb shell cmd package install-existing com.google.android.apps.tachyon
adb shell cmd package install-existing com.google.android.apps.turbo
adb shell cmd package install-existing com.google.android.as
adb shell cmd package install-existing com.google.android.as.oss
adb shell cmd package install-existing com.google.android.cellbroadcastreceiver
adb shell cmd package install-existing com.google.android.feedback
adb shell cmd package install-existing com.google.android.googlequicksearchbox
adb shell cmd package install-existing com.google.android.healthconnect.controller
adb shell cmd package install-existing com.google.android.nearby.halfsheet
adb shell cmd package install-existing com.google.android.partnersetup
adb shell cmd package install-existing com.google.android.printservice.recommendation
adb shell cmd package install-existing com.google.android.projection.gearhead
adb shell cmd package install-existing com.google.android.setupwizard
adb shell cmd package install-existing com.google.android.tts
adb shell cmd package install-existing com.google.android.youtube
adb shell cmd package install-existing com.google.ar.core
adb shell cmd package install-existing com.google.audio.hearing.visualization.accessibility.scribe
adb shell cmd package install-existing com.hiya.star
adb shell cmd package install-existing com.knox.vpn.proxyhandler
adb shell cmd package install-existing com.microsoft.appmanager
adb shell cmd package install-existing com.microsoft.skydrive
adb shell cmd package install-existing com.mygalaxy
adb shell cmd package install-existing com.netflix.mediaclient
adb shell cmd package install-existing com.netflix.partner.activation
adb shell cmd package install-existing com.opera.max.oem
adb shell cmd package install-existing com.osp.app.signin
adb shell cmd package install-existing com.samsung.android.accessibility.talkback
adb shell cmd package install-existing com.samsung.android.alive.service
adb shell cmd package install-existing com.samsung.android.allshare.service.fileshare
adb shell cmd package install-existing com.samsung.android.allshare.service.mediashare
adb shell cmd package install-existing com.samsung.android.app.appsedge
adb shell cmd package install-existing com.samsung.android.app.camera.sticker.facearavatar.preload
adb shell cmd package install-existing com.samsung.android.app.clipboardedge
adb shell cmd package install-existing com.samsung.android.app.cocktailbarservice
adb shell cmd package install-existing com.samsung.android.app.galaxyfinder
adb shell cmd package install-existing com.samsung.android.app.notes.addons
adb shell cmd package install-existing com.samsung.android.app.omcagent
adb shell cmd package install-existing com.samsung.android.app.reminder
adb shell cmd package install-existing com.samsung.android.app.routines
adb shell cmd package install-existing com.samsung.android.app.sharelive
adb shell cmd package install-existing com.samsung.android.app.taskedge
adb shell cmd package install-existing com.samsung.android.app.updatecenter
adb shell cmd package install-existing com.samsung.android.app.watchmanagerstub
adb shell cmd package install-existing com.samsung.android.ardrawing
adb shell cmd package install-existing com.samsung.android.aremoji
adb shell cmd package install-existing com.samsung.android.aremojieditor
adb shell cmd package install-existing com.samsung.android.arzone
adb shell cmd package install-existing com.samsung.android.aware.service
adb shell cmd package install-existing com.samsung.android.beaconmanager
adb shell cmd package install-existing com.samsung.android.bixbyvision.framework
adb shell cmd package install-existing com.samsung.android.da.daagent
adb shell cmd package install-existing com.samsung.android.dynamiclock
adb shell cmd package install-existing com.samsung.android.easysetup
adb shell cmd package install-existing com.samsung.android.fmm
adb shell cmd package install-existing com.samsung.android.game.gamehome
adb shell cmd package install-existing com.samsung.android.game.gametools
adb shell cmd package install-existing com.samsung.android.ipsgeofence
adb shell cmd package install-existing com.samsung.android.kidsinstaller
adb shell cmd package install-existing com.samsung.android.knox.analytics.uploader
adb shell cmd package install-existing com.samsung.android.knox.containercore
adb shell cmd package install-existing com.samsung.android.knox.kpecore
adb shell cmd package install-existing com.samsung.android.livestickers
adb shell cmd package install-existing com.samsung.android.location
adb shell cmd package install-existing com.samsung.android.mapsagent
adb shell cmd package install-existing com.samsung.android.mcfds
adb shell cmd package install-existing com.samsung.android.mdm
adb shell cmd package install-existing com.samsung.android.mdx
adb shell cmd package install-existing com.samsung.android.mfi
adb shell cmd package install-existing com.samsung.android.mobileservice
adb shell cmd package install-existing com.samsung.android.privateshare
adb shell cmd package install-existing com.samsung.android.rubin.app
adb shell cmd package install-existing com.samsung.android.samsungpass
adb shell cmd package install-existing com.samsung.android.samsungpassautofill
adb shell cmd package install-existing com.samsung.android.scloud
adb shell cmd package install-existing com.samsung.android.scs
adb shell cmd package install-existing com.samsung.android.sdk.handwriting
adb shell cmd package install-existing com.samsung.android.service.peoplestripe
adb shell cmd package install-existing com.samsung.android.service.stplatform
adb shell cmd package install-existing com.samsung.android.setting.multisound
adb shell cmd package install-existing com.samsung.android.setupindiaservicestnc
adb shell cmd package install-existing com.samsung.android.shortcutbackupservice
adb shell cmd package install-existing com.samsung.android.singletake.service
adb shell cmd package install-existing com.samsung.android.sm.devicesecurity
adb shell cmd package install-existing com.samsung.android.smartcallprovider
adb shell cmd package install-existing com.samsung.android.smartface
adb shell cmd package install-existing com.samsung.android.smartswitchassistant
adb shell cmd package install-existing com.samsung.android.spayfw
adb shell cmd package install-existing com.samsung.android.spaymini
adb shell cmd package install-existing com.samsung.android.stickercenter
adb shell cmd package install-existing com.samsung.android.themecenter
adb shell cmd package install-existing com.samsung.android.themestore
adb shell cmd package install-existing com.samsung.android.uds
adb shell cmd package install-existing com.samsung.android.visionintelligence
adb shell cmd package install-existing com.samsung.android.visualars
adb shell cmd package install-existing com.samsung.clipboardsaveservice
adb shell cmd package install-existing com.samsung.discover
adb shell cmd package install-existing com.samsung.ecomm.global.in
adb shell cmd package install-existing com.samsung.gpuwatchapp
adb shell cmd package install-existing com.samsung.klmsagent
adb shell cmd package install-existing com.samsung.memorysaver
adb shell cmd package install-existing com.samsung.sec.android.application.csc
adb shell cmd package install-existing com.samsung.SMT
adb shell cmd package install-existing com.samsung.storyservice
adb shell cmd package install-existing com.sec.android.app.billing
adb shell cmd package install-existing com.sec.android.app.chromecustomizations
adb shell cmd package install-existing com.sec.android.app.DataCreate
adb shell cmd package install-existing com.sec.android.app.fm
adb shell cmd package install-existing com.sec.android.app.kidshome
adb shell cmd package install-existing com.sec.android.app.magnifier
adb shell cmd package install-existing com.sec.android.app.quicktool
adb shell cmd package install-existing com.sec.android.app.samsungapps
adb shell cmd package install-existing com.sec.android.app.soundalive
adb shell cmd package install-existing com.sec.android.app.wlantest
adb shell cmd package install-existing com.sec.android.autodoodle.service
adb shell cmd package install-existing com.sec.android.daemonapp
adb shell cmd package install-existing com.sec.android.easyMover
adb shell cmd package install-existing com.sec.android.easyMover.Agent
adb shell cmd package install-existing com.sec.android.easyonehand
adb shell cmd package install-existing com.sec.android.mimage.avatarstickers
adb shell cmd package install-existing com.sec.android.smartfpsadjuster
adb shell cmd package install-existing com.sec.android.widgetapp.webmanual
adb shell cmd package install-existing com.sec.automation
adb shell cmd package install-existing com.sec.enterprise.knox.cloudmdm.smdms
adb shell cmd package install-existing com.sec.hearingadjust
adb shell cmd package install-existing com.sec.location.nsflp2
adb shell cmd package install-existing com.sec.mhs.smarttethering
adb shell cmd package install-existing com.sec.spp.push
adb shell cmd package install-existing com.snap.camerakit.plugin.v1                            #Snapchat Camera Kit
echo Completed Action
echo Killing adb server
adb kill-server
echo Press any key to exit terminal.
pause 
