echo Revert for Heavy Debloat Script by invinciblevenom@github
echo =============================================
echo Checking connected devices
adb devices
adb shell cmd package install-existing com.amazon.fv
adb shell cmd package install-existing com.amazon.kindle
adb shell cmd package install-existing com.amazon.mShop.android
adb shell cmd package install-existing com.amazon.mp3
adb shell cmd package install-existing com.amazon.venezia
adb shell cmd package install-existing com.android.backupconfirm
adb shell cmd package install-existing com.android.bips
adb shell cmd package install-existing com.android.chrome
adb shell cmd package install-existing com.android.dreams.basic
adb shell cmd package install-existing com.android.dreams.phototable
adb shell cmd package install-existing com.android.dreams.phototable
adb shell cmd package install-existing com.android.email
adb shell cmd package install-existing com.android.exchange
adb shell cmd package install-existing com.android.hotwordenrollment.okgoogle
adb shell cmd package install-existing com.android.printspooler
adb shell cmd package install-existing com.android.providers.partnerbookmarks
adb shell cmd package install-existing com.android.providers.userdictionary
adb shell cmd package install-existing com.android.sharedstoragebackup
adb shell cmd package install-existing com.android.stk
adb shell cmd package install-existing com.android.wallpaper.livepicker
adb shell cmd package install-existing com.android.wallpapercropper
adb shell cmd package install-existing com.audible.application
adb shell cmd package install-existing com.blurb.checkout
adb shell cmd package install-existing com.cequint.ecid
adb shell cmd package install-existing com.cnn.mobile.android.phone.edgepanel
adb shell cmd package install-existing com.diotek.sec.lookup.dictionary
adb shell cmd package install-existing com.dsi.ant.plugins.antplus
adb shell cmd package install-existing com.dsi.ant.sample.acquirechannels
adb shell cmd package install-existing com.dsi.ant.server
adb shell cmd package install-existing com.dsi.ant.service.socket
adb shell cmd package install-existing com.enhance.gameservice
adb shell cmd package install-existing com.facebook.appmanager
adb shell cmd package install-existing com.facebook.katana
adb shell cmd package install-existing com.facebook.services
adb shell cmd package install-existing com.facebook.system
adb shell cmd package install-existing com.flipboard.app
adb shell cmd package install-existing com.flipboard.boxer.app
adb shell cmd package install-existing com.google.android.apps.books
adb shell cmd package install-existing com.google.android.apps.docs
adb shell cmd package install-existing com.google.android.apps.magazines
adb shell cmd package install-existing com.google.android.apps.maps
adb shell cmd package install-existing com.google.android.apps.plus
adb shell cmd package install-existing com.google.android.apps.tachyon
adb shell cmd package install-existing com.google.android.apps.tachyon
adb shell cmd package install-existing com.google.android.apps.youtube.music
adb shell cmd package install-existing com.google.android.gm
adb shell cmd package install-existing com.google.android.googlequicksearchbox
adb shell cmd package install-existing com.google.android.printservice.recommendation
adb shell cmd package install-existing com.google.android.talk
adb shell cmd package install-existing com.google.android.tts
adb shell cmd package install-existing com.google.android.videos
adb shell cmd package install-existing com.google.android.videos
adb shell cmd package install-existing com.google.android.youtube
adb shell cmd package install-existing com.google.ar.core
adb shell cmd package install-existing com.google.vr.vrcore
adb shell cmd package install-existing com.gotv.nflgamecenter.us.lite
adb shell cmd package install-existing com.hancom.office.editor.hidden
adb shell cmd package install-existing com.hancom.office.editor.hidden
adb shell cmd package install-existing com.imdb.mobile
adb shell cmd package install-existing com.infraware.polarisoffice5
adb shell cmd package install-existing com.linkedin.android
adb shell cmd package install-existing com.microsoft.appmanager
adb shell cmd package install-existing com.microsoft.office.excel
adb shell cmd package install-existing com.microsoft.office.officehubrow
adb shell cmd package install-existing com.microsoft.office.outlook
adb shell cmd package install-existing com.microsoft.office.powerpoint
adb shell cmd package install-existing com.microsoft.office.word
adb shell cmd package install-existing com.microsoft.skydrive
adb shell cmd package install-existing com.mobeam.barcodeService
adb shell cmd package install-existing com.monotype.android.font.chococooky
adb shell cmd package install-existing com.monotype.android.font.cooljazz
adb shell cmd package install-existing com.monotype.android.font.foundation
adb shell cmd package install-existing com.monotype.android.font.rosemary
adb shell cmd package install-existing com.netflix.mediaclient
adb shell cmd package install-existing com.nuance.swype.input
adb shell cmd package install-existing com.osp.app.signin
adb shell cmd package install-existing com.policydm
adb shell cmd package install-existing com.samsung.SMT
adb shell cmd package install-existing com.samsung.aasaservice
adb shell cmd package install-existing com.samsung.android.aircommandmanager
adb shell cmd package install-existing com.samsung.android.allshare.service.fileshare
adb shell cmd package install-existing com.samsung.android.allshare.service.mediashare
adb shell cmd package install-existing com.samsung.android.app.advsounddetector
adb shell cmd package install-existing com.samsung.android.app.appsedge
adb shell cmd package install-existing com.samsung.android.app.assistantmenu
adb shell cmd package install-existing com.samsung.android.app.camera.sticker.facear.preload
adb shell cmd package install-existing com.samsung.android.app.camera.sticker.facear3d.preload
adb shell cmd package install-existing com.samsung.android.app.camera.sticker.facearavatar.preload
adb shell cmd package install-existing com.samsung.android.app.camera.sticker.facearframe.preload
adb shell cmd package install-existing com.samsung.android.app.camera.sticker.stamp.preload
adb shell cmd package install-existing com.samsung.android.app.clipboardedge
adb shell cmd package install-existing com.samsung.android.app.cocktailbarservice
adb shell cmd package install-existing com.samsung.android.app.episodes
adb shell cmd package install-existing com.samsung.android.app.filterinstaller
adb shell cmd package install-existing com.samsung.android.app.galaxyfinder
adb shell cmd package install-existing com.samsung.android.app.ledbackcover
adb shell cmd package install-existing com.samsung.android.app.ledcoverdream
adb shell cmd package install-existing com.samsung.android.app.memo
adb shell cmd package install-existing com.samsung.android.app.mirrorlink
adb shell cmd package install-existing com.samsung.android.app.notes
adb shell cmd package install-existing com.samsung.android.app.notes
adb shell cmd package install-existing com.samsung.android.app.reminder
adb shell cmd package install-existing com.samsung.android.app.routines
adb shell cmd package install-existing com.samsung.android.app.sbrowseredge
adb shell cmd package install-existing com.samsung.android.app.settings.bixby
adb shell cmd package install-existing com.samsung.android.app.sharelive
adb shell cmd package install-existing com.samsung.android.app.simplesharing
adb shell cmd package install-existing com.samsung.android.app.soundpicker
adb shell cmd package install-existing com.samsung.android.app.spage
adb shell cmd package install-existing com.samsung.android.app.storyalbumwidget
adb shell cmd package install-existing com.samsung.android.app.talkback
adb shell cmd package install-existing com.samsung.android.app.taskedge
adb shell cmd package install-existing com.samsung.android.app.tips
adb shell cmd package install-existing com.samsung.android.app.vrsetupwizardstub
adb shell cmd package install-existing com.samsung.android.app.watchmanager
adb shell cmd package install-existing com.samsung.android.app.watchmanagerstub
adb shell cmd package install-existing com.samsung.android.app.withtv
adb shell cmd package install-existing com.samsung.android.ardrawing
adb shell cmd package install-existing com.samsung.android.aremoji
adb shell cmd package install-existing com.samsung.android.arzone
adb shell cmd package install-existing com.samsung.android.authfw
adb shell cmd package install-existing com.samsung.android.aware.service
adb shell cmd package install-existing com.samsung.android.bbc.bbcagent
adb shell cmd package install-existing com.samsung.android.beaconmanager
adb shell cmd package install-existing com.samsung.android.bixby.agent
adb shell cmd package install-existing com.samsung.android.bixby.agent.dummy
adb shell cmd package install-existing com.samsung.android.bixby.es.globalaction
adb shell cmd package install-existing com.samsung.android.bixby.plmsync
adb shell cmd package install-existing com.samsung.android.bixby.service
adb shell cmd package install-existing com.samsung.android.bixby.voiceinput
adb shell cmd package install-existing com.samsung.android.bixby.wakeup
adb shell cmd package install-existing com.samsung.android.bixbyvision.framework
adb shell cmd package install-existing com.samsung.android.calendar
adb shell cmd package install-existing com.samsung.android.da.daagent
adb shell cmd package install-existing com.samsung.android.dlp.service
adb shell cmd package install-existing com.samsung.android.drivelink.stub
adb shell cmd package install-existing com.samsung.android.easysetup
adb shell cmd package install-existing com.samsung.android.email.provider
adb shell cmd package install-existing com.samsung.android.fmm
adb shell cmd package install-existing com.samsung.android.game.gamehome
adb shell cmd package install-existing com.samsung.android.game.gametools
adb shell cmd package install-existing com.samsung.android.game.gos
adb shell cmd package install-existing com.samsung.android.gametuner.thin
adb shell cmd package install-existing com.samsung.android.hmt.vrshell
adb shell cmd package install-existing com.samsung.android.hmt.vrsvc
adb shell cmd package install-existing com.samsung.android.keyguardwallpaperupdator
adb shell cmd package install-existing com.samsung.android.kidsinstaller
adb shell cmd package install-existing com.samsung.android.knox.analytics.uploader
adb shell cmd package install-existing com.samsung.android.mateagent
adb shell cmd package install-existing com.samsung.android.rajaampat
adb shell cmd package install-existing com.srin.indramayu
adb shell cmd package install-existing com.samsung.android.mdm
adb shell cmd package install-existing com.samsung.android.mdx
adb shell cmd package install-existing com.samsung.android.mdx.kit
adb shell cmd package install-existing com.samsung.android.messaging
adb shell cmd package install-existing com.samsung.android.mobileservice
adb shell cmd package install-existing com.samsung.android.oneconnect
adb shell cmd package install-existing com.samsung.android.oneconnect
adb shell cmd package install-existing com.samsung.android.samsungpass
adb shell cmd package install-existing com.samsung.android.samsungpassautofill
adb shell cmd package install-existing com.samsung.android.scloud
adb shell cmd package install-existing com.samsung.android.sdk.professionalaudio.utility.jammonitor
adb shell cmd package install-existing com.samsung.android.server.iris
adb shell cmd package install-existing com.samsung.android.service.livedrawing
adb shell cmd package install-existing com.samsung.android.service.peoplestripe
adb shell cmd package install-existing com.samsung.android.service.travel
adb shell cmd package install-existing com.samsung.android.setting.multisound
adb shell cmd package install-existing com.samsung.android.spay
adb shell cmd package install-existing com.samsung.android.spay
adb shell cmd package install-existing com.samsung.android.spayfw
adb shell cmd package install-existing com.samsung.android.spdfnote
adb shell cmd package install-existing com.samsung.android.stickercenter
adb shell cmd package install-existing com.samsung.android.stickerplugin
adb shell cmd package install-existing com.samsung.android.svoice
adb shell cmd package install-existing com.samsung.android.svoiceime
adb shell cmd package install-existing com.samsung.android.themecenter
adb shell cmd package install-existing com.samsung.android.themestore
adb shell cmd package install-existing com.samsung.android.tripwidget
adb shell cmd package install-existing com.samsung.android.visionarapps
adb shell cmd package install-existing com.samsung.android.visioncloudagent
adb shell cmd package install-existing com.samsung.android.visionintelligence
adb shell cmd package install-existing com.samsung.android.voc
adb shell cmd package install-existing com.samsung.android.voicewakeup
adb shell cmd package install-existing com.samsung.android.forest
adb shell cmd package install-existing com.samsung.android.widgetapp.yahooedge.finance
adb shell cmd package install-existing com.samsung.android.widgetapp.yahooedge.sport
adb shell cmd package install-existing com.samsung.app.highlightplayer
adb shell cmd package install-existing com.samsung.daydream.customization
adb shell cmd package install-existing com.samsung.dcmservice
adb shell cmd package install-existing com.samsung.desktopsystemui
adb shell cmd package install-existing com.samsung.enhanceservice
adb shell cmd package install-existing com.samsung.faceservice
adb shell cmd package install-existing com.samsung.fresco.logging
adb shell cmd package install-existing com.samsung.groupcast
adb shell cmd package install-existing com.samsung.hs20provider
adb shell cmd package install-existing com.samsung.ipservice
adb shell cmd package install-existing com.samsung.knox.appsupdateagent
adb shell cmd package install-existing com.samsung.knox.rcp.components
adb shell cmd package install-existing com.samsung.knox.securefolder
adb shell cmd package install-existing com.samsung.knox.securefolder.setuppage
adb shell cmd package install-existing com.samsung.safetyinformation
adb shell cmd package install-existing com.samsung.sec.android.application.csc
adb shell cmd package install-existing com.samsung.sree
adb shell cmd package install-existing com.samsung.storyservice
adb shell cmd package install-existing com.samsung.svoice.sync
adb shell cmd package install-existing com.samsung.systemui.bixby
adb shell cmd package install-existing com.samsung.systemui.bixby2
adb shell cmd package install-existing com.samsung.ucs.agent.ese
adb shell cmd package install-existing com.samsung.voiceserviceplatform
adb shell cmd package install-existing com.sec.android.AutoPreconfig
adb shell cmd package install-existing com.sec.android.Preconfig
adb shell cmd package install-existing com.sec.android.RilServiceModeApp
adb shell cmd package install-existing com.sec.android.app.DataCreate
adb shell cmd package install-existing com.sec.android.app.SecSetupWizard
adb shell cmd package install-existing com.sec.android.app.SmartClipEdgeService
adb shell cmd package install-existing com.sec.android.app.apex
adb shell cmd package install-existing com.sec.android.app.applinker
adb shell cmd package install-existing com.sec.android.app.billing
adb shell cmd package install-existing com.sec.android.app.bluetoothtest
adb shell cmd package install-existing com.sec.android.app.chromecustomizations
adb shell cmd package install-existing com.sec.android.app.clockpackage
adb shell cmd package install-existing com.sec.android.app.desktoplauncher
adb shell cmd package install-existing com.sec.android.app.dexonpc
adb shell cmd package install-existing com.sec.android.app.factorykeystring
adb shell cmd package install-existing com.sec.android.app.gamehub
adb shell cmd package install-existing com.sec.android.app.hwmoduletest
adb shell cmd package install-existing com.sec.android.app.magnifier
adb shell cmd package install-existing com.sec.android.app.myfiles
adb shell cmd package install-existing com.sec.android.app.ocr
adb shell cmd package install-existing com.sec.android.app.parser
adb shell cmd package install-existing com.sec.android.app.personalization
adb shell cmd package install-existing com.sec.android.app.popupcalculator
adb shell cmd package install-existing com.sec.android.app.popupcalculator
adb shell cmd package install-existing com.sec.android.app.quicktool
adb shell cmd package install-existing com.sec.android.app.ringtoneBR
adb shell cmd package install-existing com.sec.android.app.safetyassurance
adb shell cmd package install-existing com.sec.android.app.samsungapps
adb shell cmd package install-existing com.sec.android.app.sbrowser
adb shell cmd package install-existing com.sec.android.app.servicemodeapp
adb shell cmd package install-existing com.sec.android.app.shealth
adb shell cmd package install-existing com.sec.android.app.shealth
adb shell cmd package install-existing com.sec.android.app.soundalive
adb shell cmd package install-existing com.sec.android.app.sysscope
adb shell cmd package install-existing com.sec.android.app.tfunlock
adb shell cmd package install-existing com.sec.android.app.tourviewer
adb shell cmd package install-existing com.sec.android.app.translator
adb shell cmd package install-existing com.sec.android.app.ve.vebgm
adb shell cmd package install-existing com.sec.android.app.wfdbroker
adb shell cmd package install-existing com.sec.android.app.withtv
adb shell cmd package install-existing com.sec.android.app.wlantest
adb shell cmd package install-existing com.sec.android.cover.ledcover
adb shell cmd package install-existing com.sec.android.desktopmode.uiservice
adb shell cmd package install-existing com.sec.android.diagmonagent
adb shell cmd package install-existing com.sec.android.easyMover
adb shell cmd package install-existing com.sec.android.easyMover
adb shell cmd package install-existing com.sec.android.easyMover.Agent
adb shell cmd package install-existing com.sec.android.easyonehand
adb shell cmd package install-existing com.sec.android.emergencylauncher
adb shell cmd package install-existing com.sec.android.mimage.avatarstickers
adb shell cmd package install-existing com.sec.android.mimage.gear360editor
adb shell cmd package install-existing com.sec.android.mimage.photoretouching
adb shell cmd package install-existing com.sec.android.ofviewer
adb shell cmd package install-existing com.sec.android.omc
adb shell cmd package install-existing com.sec.android.preloadinstaller
adb shell cmd package install-existing com.sec.android.provider.snote
adb shell cmd package install-existing com.sec.android.providers.security
adb shell cmd package install-existing com.sec.android.providers.tasks
adb shell cmd package install-existing com.sec.android.sdhms
adb shell cmd package install-existing com.sec.android.service.health
adb shell cmd package install-existing com.sec.android.sidesync30
adb shell cmd package install-existing com.sec.android.splitsound
adb shell cmd package install-existing com.sec.android.uibcvirtualsoftkey
adb shell cmd package install-existing com.sec.android.widgetapp.diotek.smemo
adb shell cmd package install-existing com.sec.android.widgetapp.easymodecontactswidget
adb shell cmd package install-existing com.sec.android.widgetapp.samsungapps
adb shell cmd package install-existing com.sec.app.TransmitPowerService
adb shell cmd package install-existing com.sec.automation
adb shell cmd package install-existing com.sec.bcservice
adb shell cmd package install-existing com.sec.downloadablekeystore
adb shell cmd package install-existing com.sec.enterprise.knox.attestation
adb shell cmd package install-existing com.sec.enterprise.knox.cloudmdm.smdms
adb shell cmd package install-existing com.sec.enterprise.mdm.services.simpin
adb shell cmd package install-existing com.sec.enterprise.mdm.vpn
adb shell cmd package install-existing com.sec.epdgtestapp
adb shell cmd package install-existing com.sec.everglades
adb shell cmd package install-existing com.sec.everglades.update
adb shell cmd package install-existing com.sec.factory
adb shell cmd package install-existing com.sec.factory.camera
adb shell cmd package install-existing com.sec.factory.iris.usercamera
adb shell cmd package install-existing com.sec.hearingadjust
adb shell cmd package install-existing com.sec.kidsplat.installer
adb shell cmd package install-existing com.sec.knox.foldercontainer
adb shell cmd package install-existing com.sec.knox.knoxsetupwizardclient
adb shell cmd package install-existing com.sec.knox.switcher
adb shell cmd package install-existing com.sec.location.nsflp2
adb shell cmd package install-existing com.sec.mldapchecker
adb shell cmd package install-existing com.sec.modem.settings
adb shell cmd package install-existing com.sec.providers.assisteddialing
adb shell cmd package install-existing com.sec.readershub
adb shell cmd package install-existing com.sec.smartcard.manager
adb shell cmd package install-existing com.sec.spen.flashannotate
adb shell cmd package install-existing com.sec.spp.push
adb shell cmd package install-existing com.sec.sve
adb shell cmd package install-existing com.sec.usbsettings
adb shell cmd package install-existing com.sec.vowifispg
adb shell cmd package install-existing com.sec.yosemite.phone
adb shell cmd package install-existing com.sem.factoryapp
adb shell cmd package install-existing com.singtel.mysingtel
adb shell cmd package install-existing com.skms.android.agent
adb shell cmd package install-existing com.skype.raider
adb shell cmd package install-existing com.test.LTEfunctionality
adb shell cmd package install-existing com.touchtype.swiftkey
adb shell cmd package install-existing com.tripadvisor.tripadvisor
adb shell cmd package install-existing com.trustonic.tuiservice
adb shell cmd package install-existing com.tv.peel.samsung.app
adb shell cmd package install-existing com.vlingo.midas
adb shell cmd package install-existing com.wssnps
adb shell cmd package install-existing com.yelp.android.samsungedge
adb shell cmd package install-existing com.android.apps.tag
adb shell cmd package install-existing com.android.bips
adb shell cmd package install-existing com.android.bookmarkprovider
adb shell cmd package install-existing com.android.chrome
adb shell cmd package install-existing com.android.dreams.phototable
adb shell cmd package install-existing com.android.hotwordenrollment.okgoogle
adb shell cmd package install-existing com.android.hotwordenrollment.xgoogle
adb shell cmd package install-existing com.android.internal.display.cutout.emulation.waterfall
adb shell cmd package install-existing com.android.printspooler
adb shell cmd package install-existing com.android.providers.calendar
adb shell cmd package install-existing com.android.providers.partnerbookmarks
adb shell cmd package install-existing com.android.role.notes.enabled
adb shell cmd package install-existing com.android.settings.intelligence
adb shell cmd package install-existing com.facebook.appmanager
adb shell cmd package install-existing com.facebook.katana
adb shell cmd package install-existing com.facebook.services
adb shell cmd package install-existing com.facebook.system
adb shell cmd package install-existing com.google.android.aicore
adb shell cmd package install-existing com.google.android.apps.accessibility.voiceaccess
adb shell cmd package install-existing com.google.android.apps.aiwallpapers
adb shell cmd package install-existing com.google.android.apps.bard
adb shell cmd package install-existing com.google.android.apps.docs
adb shell cmd package install-existing com.google.android.apps.photos
adb shell cmd package install-existing com.google.android.apps.restore
adb shell cmd package install-existing com.google.android.apps.tachyon
adb shell cmd package install-existing com.google.android.apps.youtube.music
adb shell cmd package install-existing com.google.android.feedback
adb shell cmd package install-existing com.google.android.gm
adb shell cmd package install-existing com.google.android.gms.supervision
adb shell cmd package install-existing com.google.android.googlequicksearchbox
adb shell cmd package install-existing com.google.android.healthconnect.controller
adb shell cmd package install-existing com.google.android.onetimeinitializer
adb shell cmd package install-existing com.google.android.partnersetup
adb shell cmd package install-existing com.google.android.printservice.recommendation
adb shell cmd package install-existing com.google.android.projection.gearhead
adb shell cmd package install-existing com.google.android.safetycenter.resources
adb shell cmd package install-existing com.google.android.syncadapters.calendar
adb shell cmd package install-existing com.google.android.tts
adb shell cmd package install-existing com.google.android.videos
adb shell cmd package install-existing com.google.android.youtube
adb shell cmd package install-existing com.google.ar.core
adb shell cmd package install-existing com.google.audio.hearing.visualization.accessibility.scribe
adb shell cmd package install-existing com.google.mainline.telemetry
adb shell cmd package install-existing com.linkedin.android
adb shell cmd package install-existing com.microsoft.appmanager
adb shell cmd package install-existing com.microsoft.office.officehubrow
adb shell cmd package install-existing com.microsoft.office.outlook
adb shell cmd package install-existing com.microsoft.skydrive
adb shell cmd package install-existing com.monotype.android.font.samsungone
adb shell cmd package install-existing com.netflix.mediaclient
adb shell cmd package install-existing com.osp.app.signin
adb shell cmd package install-existing com.samsung.android.aicore
adb shell cmd package install-existing com.samsung.android.app.find
adb shell cmd package install-existing com.samsung.android.app.interpreter
adb shell cmd package install-existing com.samsung.android.app.notes
adb shell cmd package install-existing com.samsung.android.app.omcagent
adb shell cmd package install-existing com.samsung.android.app.parentalcare
adb shell cmd package install-existing com.samsung.android.app.readingglass
adb shell cmd package install-existing com.samsung.android.app.sketchbook
adb shell cmd package install-existing com.samsung.android.app.spage
adb shell cmd package install-existing com.samsung.android.app.tips
adb shell cmd package install-existing com.samsung.android.app.updatecenter
adb shell cmd package install-existing com.samsung.android.app.watchmanager
adb shell cmd package install-existing com.samsung.android.aremoji
adb shell cmd package install-existing com.samsung.android.aremojieditor
adb shell cmd package install-existing com.samsung.android.authfw
adb shell cmd package install-existing com.samsung.android.bixby.agent
adb shell cmd package install-existing com.samsung.android.bixby.ondevice.enus
adb shell cmd package install-existing com.samsung.android.bixby.ondevice.esus
adb shell cmd package install-existing com.samsung.android.bixby.wakeup
adb shell cmd package install-existing com.samsung.android.bixbyvision.framework
adb shell cmd package install-existing com.samsung.android.carkey
adb shell cmd package install-existing com.samsung.android.coldwalletservice
adb shell cmd package install-existing com.samsung.android.da.daagent
adb shell cmd package install-existing com.samsung.android.dbsc
adb shell cmd package install-existing com.samsung.android.dkey
adb shell cmd package install-existing com.samsung.android.ese
adb shell cmd package install-existing com.samsung.android.fmm
adb shell cmd package install-existing com.samsung.android.game.gamehome
adb shell cmd package install-existing com.samsung.android.game.gametools
adb shell cmd package install-existing com.samsung.android.game.gos
adb shell cmd package install-existing com.samsung.android.globalpostprocmgr
adb shell cmd package install-existing com.samsung.android.gru
adb shell cmd package install-existing com.samsung.android.hwresourceshare.storage
adb shell cmd package install-existing com.samsung.android.intellivoiceservice
adb shell cmd package install-existing com.samsung.android.ipsgeofence
adb shell cmd package install-existing com.samsung.android.kidsinstaller
adb shell cmd package install-existing com.samsung.android.knox.zt.framework
adb shell cmd package install-existing com.samsung.android.liveeffectservice
adb shell cmd package install-existing com.samsung.android.mapsagent
adb shell cmd package install-existing com.samsung.android.mdecservice
adb shell cmd package install-existing com.samsung.android.mdx
adb shell cmd package install-existing com.samsung.android.net.wifi.wifiguider
adb shell cmd package install-existing com.samsung.android.nmt.apps.t2t.languagepack.enesus
adb shell cmd package install-existing com.samsung.android.offline.languagemodel
adb shell cmd package install-existing com.samsung.android.oneconnect
adb shell cmd package install-existing com.samsung.android.samsungpass
adb shell cmd package install-existing com.samsung.android.samsungpassautofill
adb shell cmd package install-existing com.samsung.android.scloud
adb shell cmd package install-existing com.samsung.android.scpm
adb shell cmd package install-existing com.samsung.android.sdk.ocr
adb shell cmd package install-existing com.samsung.android.service.peoplestripe
adb shell cmd package install-existing com.samsung.android.service.stplatform
adb shell cmd package install-existing com.samsung.android.service.tagservice
adb shell cmd package install-existing com.samsung.android.smartmirroring
adb shell cmd package install-existing com.samsung.android.smartsuggestions
adb shell cmd package install-existing com.samsung.android.smartswitchassistant
adb shell cmd package install-existing com.samsung.android.spay
adb shell cmd package install-existing com.samsung.android.spayfw
adb shell cmd package install-existing com.samsung.android.ssco
adb shell cmd package install-existing com.samsung.android.stickercenter
adb shell cmd package install-existing com.samsung.android.tvplus
adb shell cmd package install-existing com.samsung.android.vision.model
adb shell cmd package install-existing com.samsung.android.visionintelligence
adb shell cmd package install-existing com.samsung.android.visual.cloudcore
adb shell cmd package install-existing com.samsung.android.voc
adb shell cmd package install-existing com.samsung.android.vtcamerasettings
adb shell cmd package install-existing com.samsung.app.newtrim
adb shell cmd package install-existing com.samsung.ecomm
adb shell cmd package install-existing com.samsung.petservice
adb shell cmd package install-existing com.samsung.sree
adb shell cmd package install-existing com.samsung.storyservice
adb shell cmd package install-existing com.sec.android.app.billing
adb shell cmd package install-existing com.sec.android.app.desktoplauncher
adb shell cmd package install-existing com.sec.android.app.kidshome
adb shell cmd package install-existing com.sec.android.app.magnifier
adb shell cmd package install-existing com.sec.android.app.samsungapps
adb shell cmd package install-existing com.sec.android.app.sbrowser
adb shell cmd package install-existing com.sec.android.app.setupwizard
adb shell cmd package install-existing com.sec.android.app.shealth
adb shell cmd package install-existing com.sec.android.app.ve.vebgm
adb shell cmd package install-existing com.sec.android.app.vepreload
adb shell cmd package install-existing com.sec.android.app.voicenote
adb shell cmd package install-existing com.sec.android.autodoodle.service
adb shell cmd package install-existing com.sec.android.desktopmode.uiservice
adb shell cmd package install-existing com.sec.android.dexsystemui
adb shell cmd package install-existing com.sec.android.easyMover
adb shell cmd package install-existing com.sec.android.easyonehand
adb shell cmd package install-existing com.sec.android.mimage.avatarstickers
adb shell cmd package install-existing com.sec.android.mimage.photoretouching
adb shell cmd package install-existing com.sec.location.nsflp2
adb shell cmd package install-existing com.sec.penup
adb shell cmd package install-existing com.spotify.music
echo All changes have been reverted.
echo Killing adb server
adb kill-server
echo Press any key to exit terminal.
pause 
