echo Heavy Debloat Script by invinciblevenom
adb devices
adb shell pm uninstall -k --user 0 com.amazon.fv
adb shell pm uninstall -k --user 0 com.amazon.kindle
adb shell pm uninstall -k --user 0 com.amazon.mShop.android
adb shell pm uninstall -k --user 0 com.amazon.mp3
adb shell pm uninstall -k --user 0 com.amazon.venezia
adb shell pm uninstall -k --user 0 com.android.backupconfirm
adb shell pm uninstall -k --user 0 com.android.bips
adb shell pm uninstall -k --user 0 com.android.chrome
adb shell pm uninstall -k --user 0 com.android.dreams.basic
adb shell pm uninstall -k --user 0 com.android.dreams.phototable
adb shell pm uninstall -k --user 0 com.android.dreams.phototable
adb shell pm uninstall -k --user 0 com.android.email
adb shell pm uninstall -k --user 0 com.android.exchange
adb shell pm uninstall -k --user 0 com.android.hotwordenrollment.okgoogle
adb shell pm uninstall -k --user 0 com.android.printspooler
adb shell pm uninstall -k --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall -k --user 0 com.android.providers.userdictionary
adb shell pm uninstall -k --user 0 com.android.sharedstoragebackup
adb shell pm uninstall -k --user 0 com.android.stk
adb shell pm uninstall -k --user 0 com.android.wallpaper.livepicker
adb shell pm uninstall -k --user 0 com.android.wallpapercropper
adb shell pm uninstall -k --user 0 com.audible.application
adb shell pm uninstall -k --user 0 com.blurb.checkout
adb shell pm uninstall -k --user 0 com.cequint.ecid
adb shell pm uninstall -k --user 0 com.cnn.mobile.android.phone.edgepanel
adb shell pm uninstall -k --user 0 com.diotek.sec.lookup.dictionary
adb shell pm uninstall -k --user 0 com.dsi.ant.plugins.antplus
adb shell pm uninstall -k --user 0 com.dsi.ant.sample.acquirechannels
adb shell pm uninstall -k --user 0 com.dsi.ant.server
adb shell pm uninstall -k --user 0 com.dsi.ant.service.socket
adb shell pm uninstall -k --user 0 com.enhance.gameservice
adb shell pm uninstall -k --user 0 com.facebook.appmanager
adb shell pm uninstall -k --user 0 com.facebook.katana
adb shell pm uninstall -k --user 0 com.facebook.services
adb shell pm uninstall -k --user 0 com.facebook.system
adb shell pm uninstall -k --user 0 com.flipboard.app
adb shell pm uninstall -k --user 0 com.flipboard.boxer.app
adb shell pm uninstall -k --user 0 com.google.android.apps.books
adb shell pm uninstall -k --user 0 com.google.android.apps.docs
adb shell pm uninstall -k --user 0 com.google.android.apps.magazines
adb shell pm uninstall -k --user 0 com.google.android.apps.maps
adb shell pm uninstall -k --user 0 com.google.android.apps.plus
adb shell pm uninstall -k --user 0 com.google.android.apps.tachyon
adb shell pm uninstall -k --user 0 com.google.android.apps.tachyon
adb shell pm uninstall -k --user 0 com.google.android.apps.youtube.music
adb shell pm uninstall -k --user 0 com.google.android.gm
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall -k --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall -k --user 0 com.google.android.talk
adb shell pm uninstall -k --user 0 com.google.android.tts
adb shell pm uninstall -k --user 0 com.google.android.videos
adb shell pm uninstall -k --user 0 com.google.android.videos
adb shell pm uninstall -k --user 0 com.google.android.youtube
adb shell pm uninstall -k --user 0 com.google.ar.core
adb shell pm uninstall -k --user 0 com.google.vr.vrcore
adb shell pm uninstall -k --user 0 com.gotv.nflgamecenter.us.lite
adb shell pm uninstall -k --user 0 com.hancom.office.editor.hidden
adb shell pm uninstall -k --user 0 com.hancom.office.editor.hidden
adb shell pm uninstall -k --user 0 com.imdb.mobile
adb shell pm uninstall -k --user 0 com.infraware.polarisoffice5
adb shell pm uninstall -k --user 0 com.linkedin.android
adb shell pm uninstall -k --user 0 com.microsoft.appmanager
adb shell pm uninstall -k --user 0 com.microsoft.office.excel
adb shell pm uninstall -k --user 0 com.microsoft.office.officehubrow
adb shell pm uninstall -k --user 0 com.microsoft.office.outlook
adb shell pm uninstall -k --user 0 com.microsoft.office.powerpoint
adb shell pm uninstall -k --user 0 com.microsoft.office.word
adb shell pm uninstall -k --user 0 com.microsoft.skydrive
adb shell pm uninstall -k --user 0 com.mobeam.barcodeService
adb shell pm uninstall -k --user 0 com.monotype.android.font.chococooky
adb shell pm uninstall -k --user 0 com.monotype.android.font.cooljazz
adb shell pm uninstall -k --user 0 com.monotype.android.font.foundation
adb shell pm uninstall -k --user 0 com.monotype.android.font.rosemary
adb shell pm uninstall -k --user 0 com.netflix.mediaclient
adb shell pm uninstall -k --user 0 com.nuance.swype.input
adb shell pm uninstall -k --user 0 com.osp.app.signin
adb shell pm uninstall -k --user 0 com.policydm
adb shell pm uninstall -k --user 0 com.samsung.SMT
adb shell pm uninstall -k --user 0 com.samsung.aasaservice
adb shell pm uninstall -k --user 0 com.samsung.android.aircommandmanager
adb shell pm uninstall -k --user 0 com.samsung.android.allshare.service.fileshare
adb shell pm uninstall -k --user 0 com.samsung.android.allshare.service.mediashare
adb shell pm uninstall -k --user 0 com.samsung.android.app.advsounddetector
adb shell pm uninstall -k --user 0 com.samsung.android.app.appsedge
adb shell pm uninstall -k --user 0 com.samsung.android.app.assistantmenu
adb shell pm uninstall -k --user 0 com.samsung.android.app.camera.sticker.facear.preload
adb shell pm uninstall -k --user 0 com.samsung.android.app.camera.sticker.facear3d.preload
adb shell pm uninstall -k --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload
adb shell pm uninstall -k --user 0 com.samsung.android.app.camera.sticker.facearframe.preload
adb shell pm uninstall -k --user 0 com.samsung.android.app.camera.sticker.stamp.preload
adb shell pm uninstall -k --user 0 com.samsung.android.app.clipboardedge
adb shell pm uninstall -k --user 0 com.samsung.android.app.cocktailbarservice
adb shell pm uninstall -k --user 0 com.samsung.android.app.episodes
adb shell pm uninstall -k --user 0 com.samsung.android.app.filterinstaller
adb shell pm uninstall -k --user 0 com.samsung.android.app.galaxyfinder
adb shell pm uninstall -k --user 0 com.samsung.android.app.ledbackcover
adb shell pm uninstall -k --user 0 com.samsung.android.app.ledcoverdream
adb shell pm uninstall -k --user 0 com.samsung.android.app.memo
adb shell pm uninstall -k --user 0 com.samsung.android.app.mirrorlink
adb shell pm uninstall -k --user 0 com.samsung.android.app.notes
adb shell pm uninstall -k --user 0 com.samsung.android.app.notes
adb shell pm uninstall -k --user 0 com.samsung.android.app.reminder
adb shell pm uninstall -k --user 0 com.samsung.android.app.routines
adb shell pm uninstall -k --user 0 com.samsung.android.app.sbrowseredge
adb shell pm uninstall -k --user 0 com.samsung.android.app.settings.bixby
adb shell pm uninstall -k --user 0 com.samsung.android.app.sharelive
adb shell pm uninstall -k --user 0 com.samsung.android.app.simplesharing
adb shell pm uninstall -k --user 0 com.samsung.android.app.soundpicker
adb shell pm uninstall -k --user 0 com.samsung.android.app.spage
adb shell pm uninstall -k --user 0 com.samsung.android.app.storyalbumwidget
adb shell pm uninstall -k --user 0 com.samsung.android.app.talkback
adb shell pm uninstall -k --user 0 com.samsung.android.app.taskedge
adb shell pm uninstall -k --user 0 com.samsung.android.app.tips
adb shell pm uninstall -k --user 0 com.samsung.android.app.vrsetupwizardstub
adb shell pm uninstall -k --user 0 com.samsung.android.app.watchmanager
adb shell pm uninstall -k --user 0 com.samsung.android.app.watchmanagerstub
adb shell pm uninstall -k --user 0 com.samsung.android.app.withtv
adb shell pm uninstall -k --user 0 com.samsung.android.ardrawing
adb shell pm uninstall -k --user 0 com.samsung.android.aremoji
adb shell pm uninstall -k --user 0 com.samsung.android.arzone
adb shell pm uninstall -k --user 0 com.samsung.android.authfw
adb shell pm uninstall -k --user 0 com.samsung.android.aware.service
adb shell pm uninstall -k --user 0 com.samsung.android.bbc.bbcagent
adb shell pm uninstall -k --user 0 com.samsung.android.beaconmanager
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.agent
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.agent.dummy
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.es.globalaction
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.plmsync
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.service
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.voiceinput
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.wakeup
adb shell pm uninstall -k --user 0 com.samsung.android.bixbyvision.framework
adb shell pm uninstall -k --user 0 com.samsung.android.calendar
adb shell pm uninstall -k --user 0 com.samsung.android.da.daagent
adb shell pm uninstall -k --user 0 com.samsung.android.dlp.service
adb shell pm uninstall -k --user 0 com.samsung.android.drivelink.stub
adb shell pm uninstall -k --user 0 com.samsung.android.easysetup
adb shell pm uninstall -k --user 0 com.samsung.android.email.provider
adb shell pm uninstall -k --user 0 com.samsung.android.fmm
adb shell pm uninstall -k --user 0 com.samsung.android.game.gamehome
adb shell pm uninstall -k --user 0 com.samsung.android.game.gametools
adb shell pm uninstall -k --user 0 com.samsung.android.game.gos
adb shell pm uninstall -k --user 0 com.samsung.android.gametuner.thin
adb shell pm uninstall -k --user 0 com.samsung.android.hmt.vrshell
adb shell pm uninstall -k --user 0 com.samsung.android.hmt.vrsvc
adb shell pm uninstall -k --user 0 com.samsung.android.keyguardwallpaperupdator
adb shell pm uninstall -k --user 0 com.samsung.android.kidsinstaller
adb shell pm uninstall -k --user 0 com.samsung.android.knox.analytics.uploader
adb shell pm uninstall -k --user 0 com.samsung.android.mateagent
adb shell pm uninstall -k --user 0 com.samsung.android.rajaampat
adb shell pm uninstall -k --user 0 com.srin.indramayu
adb shell pm uninstall -k --user 0 com.samsung.android.mdm
adb shell pm uninstall -k --user 0 com.samsung.android.mdx
adb shell pm uninstall -k --user 0 com.samsung.android.mdx.kit
adb shell pm uninstall -k --user 0 com.samsung.android.messaging
adb shell pm uninstall -k --user 0 com.samsung.android.mobileservice
adb shell pm uninstall -k --user 0 com.samsung.android.oneconnect
adb shell pm uninstall -k --user 0 com.samsung.android.oneconnect
adb shell pm uninstall -k --user 0 com.samsung.android.samsungpass
adb shell pm uninstall -k --user 0 com.samsung.android.samsungpassautofill
adb shell pm uninstall -k --user 0 com.samsung.android.scloud
adb shell pm uninstall -k --user 0 com.samsung.android.sdk.professionalaudio.utility.jammonitor
adb shell pm uninstall -k --user 0 com.samsung.android.server.iris
adb shell pm uninstall -k --user 0 com.samsung.android.service.livedrawing
adb shell pm uninstall -k --user 0 com.samsung.android.service.peoplestripe
adb shell pm uninstall -k --user 0 com.samsung.android.service.travel
adb shell pm uninstall -k --user 0 com.samsung.android.setting.multisound
adb shell pm uninstall -k --user 0 com.samsung.android.spay
adb shell pm uninstall -k --user 0 com.samsung.android.spay
adb shell pm uninstall -k --user 0 com.samsung.android.spayfw
adb shell pm uninstall -k --user 0 com.samsung.android.spdfnote
adb shell pm uninstall -k --user 0 com.samsung.android.stickercenter
adb shell pm uninstall -k --user 0 com.samsung.android.stickerplugin
adb shell pm uninstall -k --user 0 com.samsung.android.svoice
adb shell pm uninstall -k --user 0 com.samsung.android.svoiceime
adb shell pm uninstall -k --user 0 com.samsung.android.themecenter
adb shell pm uninstall -k --user 0 com.samsung.android.themestore
adb shell pm uninstall -k --user 0 com.samsung.android.tripwidget
adb shell pm uninstall -k --user 0 com.samsung.android.visionarapps
adb shell pm uninstall -k --user 0 com.samsung.android.visioncloudagent
adb shell pm uninstall -k --user 0 com.samsung.android.visionintelligence
adb shell pm uninstall -k --user 0 com.samsung.android.voc
adb shell pm uninstall -k --user 0 com.samsung.android.voicewakeup
adb shell pm uninstall -k --user 0 com.samsung.android.forest
adb shell pm uninstall -k --user 0 com.samsung.android.widgetapp.yahooedge.finance
adb shell pm uninstall -k --user 0 com.samsung.android.widgetapp.yahooedge.sport
adb shell pm uninstall -k --user 0 com.samsung.app.highlightplayer
adb shell pm uninstall -k --user 0 com.samsung.daydream.customization
adb shell pm uninstall -k --user 0 com.samsung.dcmservice
adb shell pm uninstall -k --user 0 com.samsung.desktopsystemui
adb shell pm uninstall -k --user 0 com.samsung.enhanceservice
adb shell pm uninstall -k --user 0 com.samsung.faceservice
adb shell pm uninstall -k --user 0 com.samsung.fresco.logging
adb shell pm uninstall -k --user 0 com.samsung.groupcast
adb shell pm uninstall -k --user 0 com.samsung.hs20provider
adb shell pm uninstall -k --user 0 com.samsung.ipservice
adb shell pm uninstall -k --user 0 com.samsung.knox.appsupdateagent
adb shell pm uninstall -k --user 0 com.samsung.knox.rcp.components
adb shell pm uninstall -k --user 0 com.samsung.knox.securefolder
adb shell pm uninstall -k --user 0 com.samsung.knox.securefolder.setuppage
adb shell pm uninstall -k --user 0 com.samsung.safetyinformation
adb shell pm uninstall -k --user 0 com.samsung.sec.android.application.csc
adb shell pm uninstall -k --user 0 com.samsung.sree
adb shell pm uninstall -k --user 0 com.samsung.storyservice
adb shell pm uninstall -k --user 0 com.samsung.svoice.sync
adb shell pm uninstall -k --user 0 com.samsung.systemui.bixby
adb shell pm uninstall -k --user 0 com.samsung.systemui.bixby2
adb shell pm uninstall -k --user 0 com.samsung.ucs.agent.ese
adb shell pm uninstall -k --user 0 com.samsung.voiceserviceplatform
adb shell pm uninstall -k --user 0 com.sec.android.AutoPreconfig
adb shell pm uninstall -k --user 0 com.sec.android.Preconfig
adb shell pm uninstall -k --user 0 com.sec.android.RilServiceModeApp
adb shell pm uninstall -k --user 0 com.sec.android.app.DataCreate
adb shell pm uninstall -k --user 0 com.sec.android.app.SecSetupWizard
adb shell pm uninstall -k --user 0 com.sec.android.app.SmartClipEdgeService
adb shell pm uninstall -k --user 0 com.sec.android.app.apex
adb shell pm uninstall -k --user 0 com.sec.android.app.applinker
adb shell pm uninstall -k --user 0 com.sec.android.app.billing
adb shell pm uninstall -k --user 0 com.sec.android.app.bluetoothtest
adb shell pm uninstall -k --user 0 com.sec.android.app.chromecustomizations
adb shell pm uninstall -k --user 0 com.sec.android.app.clockpackage
adb shell pm uninstall -k --user 0 com.sec.android.app.desktoplauncher
adb shell pm uninstall -k --user 0 com.sec.android.app.dexonpc
adb shell pm uninstall -k --user 0 com.sec.android.app.factorykeystring
adb shell pm uninstall -k --user 0 com.sec.android.app.gamehub
adb shell pm uninstall -k --user 0 com.sec.android.app.hwmoduletest
adb shell pm uninstall -k --user 0 com.sec.android.app.magnifier
adb shell pm uninstall -k --user 0 com.sec.android.app.myfiles
adb shell pm uninstall -k --user 0 com.sec.android.app.ocr
adb shell pm uninstall -k --user 0 com.sec.android.app.parser
adb shell pm uninstall -k --user 0 com.sec.android.app.personalization
adb shell pm uninstall -k --user 0 com.sec.android.app.popupcalculator
adb shell pm uninstall -k --user 0 com.sec.android.app.popupcalculator
adb shell pm uninstall -k --user 0 com.sec.android.app.quicktool
adb shell pm uninstall -k --user 0 com.sec.android.app.ringtoneBR
adb shell pm uninstall -k --user 0 com.sec.android.app.safetyassurance
adb shell pm uninstall -k --user 0 com.sec.android.app.samsungapps
adb shell pm uninstall -k --user 0 com.sec.android.app.sbrowser
adb shell pm uninstall -k --user 0 com.sec.android.app.servicemodeapp
adb shell pm uninstall -k --user 0 com.sec.android.app.shealth
adb shell pm uninstall -k --user 0 com.sec.android.app.shealth
adb shell pm uninstall -k --user 0 com.sec.android.app.soundalive
adb shell pm uninstall -k --user 0 com.sec.android.app.sysscope
adb shell pm uninstall -k --user 0 com.sec.android.app.tfunlock
adb shell pm uninstall -k --user 0 com.sec.android.app.tourviewer
adb shell pm uninstall -k --user 0 com.sec.android.app.translator
adb shell pm uninstall -k --user 0 com.sec.android.app.ve.vebgm
adb shell pm uninstall -k --user 0 com.sec.android.app.wfdbroker
adb shell pm uninstall -k --user 0 com.sec.android.app.withtv
adb shell pm uninstall -k --user 0 com.sec.android.app.wlantest
adb shell pm uninstall -k --user 0 com.sec.android.cover.ledcover
adb shell pm uninstall -k --user 0 com.sec.android.desktopmode.uiservice
adb shell pm uninstall -k --user 0 com.sec.android.diagmonagent
adb shell pm uninstall -k --user 0 com.sec.android.easyMover
adb shell pm uninstall -k --user 0 com.sec.android.easyMover
adb shell pm uninstall -k --user 0 com.sec.android.easyMover.Agent
adb shell pm uninstall -k --user 0 com.sec.android.easyonehand
adb shell pm uninstall -k --user 0 com.sec.android.emergencylauncher
adb shell pm uninstall -k --user 0 com.sec.android.mimage.avatarstickers
adb shell pm uninstall -k --user 0 com.sec.android.mimage.gear360editor
adb shell pm uninstall -k --user 0 com.sec.android.mimage.photoretouching
adb shell pm uninstall -k --user 0 com.sec.android.ofviewer
adb shell pm uninstall -k --user 0 com.sec.android.omc
adb shell pm uninstall -k --user 0 com.sec.android.preloadinstaller
adb shell pm uninstall -k --user 0 com.sec.android.provider.snote
adb shell pm uninstall -k --user 0 com.sec.android.providers.security
adb shell pm uninstall -k --user 0 com.sec.android.providers.tasks
adb shell pm uninstall -k --user 0 com.sec.android.sdhms
adb shell pm uninstall -k --user 0 com.sec.android.service.health
adb shell pm uninstall -k --user 0 com.sec.android.sidesync30
adb shell pm uninstall -k --user 0 com.sec.android.splitsound
adb shell pm uninstall -k --user 0 com.sec.android.uibcvirtualsoftkey
adb shell pm uninstall -k --user 0 com.sec.android.widgetapp.diotek.smemo
adb shell pm uninstall -k --user 0 com.sec.android.widgetapp.easymodecontactswidget
adb shell pm uninstall -k --user 0 com.sec.android.widgetapp.samsungapps
adb shell pm uninstall -k --user 0 com.sec.app.TransmitPowerService
adb shell pm uninstall -k --user 0 com.sec.automation
adb shell pm uninstall -k --user 0 com.sec.bcservice
adb shell pm uninstall -k --user 0 com.sec.downloadablekeystore
adb shell pm uninstall -k --user 0 com.sec.enterprise.knox.attestation
adb shell pm uninstall -k --user 0 com.sec.enterprise.knox.cloudmdm.smdms
adb shell pm uninstall -k --user 0 com.sec.enterprise.mdm.services.simpin
adb shell pm uninstall -k --user 0 com.sec.enterprise.mdm.vpn
adb shell pm uninstall -k --user 0 com.sec.epdgtestapp
adb shell pm uninstall -k --user 0 com.sec.everglades
adb shell pm uninstall -k --user 0 com.sec.everglades.update
adb shell pm uninstall -k --user 0 com.sec.factory
adb shell pm uninstall -k --user 0 com.sec.factory.camera
adb shell pm uninstall -k --user 0 com.sec.factory.iris.usercamera
adb shell pm uninstall -k --user 0 com.sec.hearingadjust
adb shell pm uninstall -k --user 0 com.sec.kidsplat.installer
adb shell pm uninstall -k --user 0 com.sec.knox.foldercontainer
adb shell pm uninstall -k --user 0 com.sec.knox.knoxsetupwizardclient
adb shell pm uninstall -k --user 0 com.sec.knox.switcher
adb shell pm uninstall -k --user 0 com.sec.location.nsflp2
adb shell pm uninstall -k --user 0 com.sec.mldapchecker
adb shell pm uninstall -k --user 0 com.sec.modem.settings
adb shell pm uninstall -k --user 0 com.sec.providers.assisteddialing
adb shell pm uninstall -k --user 0 com.sec.readershub
adb shell pm uninstall -k --user 0 com.sec.smartcard.manager
adb shell pm uninstall -k --user 0 com.sec.spen.flashannotate
adb shell pm uninstall -k --user 0 com.sec.spp.push
adb shell pm uninstall -k --user 0 com.sec.sve
adb shell pm uninstall -k --user 0 com.sec.usbsettings
adb shell pm uninstall -k --user 0 com.sec.vowifispg
adb shell pm uninstall -k --user 0 com.sec.yosemite.phone
adb shell pm uninstall -k --user 0 com.sem.factoryapp
adb shell pm uninstall -k --user 0 com.singtel.mysingtel
adb shell pm uninstall -k --user 0 com.skms.android.agent
adb shell pm uninstall -k --user 0 com.skype.raider
adb shell pm uninstall -k --user 0 com.test.LTEfunctionality
adb shell pm uninstall -k --user 0 com.touchtype.swiftkey
adb shell pm uninstall -k --user 0 com.tripadvisor.tripadvisor
adb shell pm uninstall -k --user 0 com.trustonic.tuiservice
adb shell pm uninstall -k --user 0 com.tv.peel.samsung.app
adb shell pm uninstall -k --user 0 com.vlingo.midas
adb shell pm uninstall -k --user 0 com.wssnps
adb shell pm uninstall -k --user 0 com.yelp.android.samsungedge
adb shell pm uninstall -k --user 0 com.android.apps.tag
adb shell pm uninstall -k --user 0 com.android.bips
adb shell pm uninstall -k --user 0 com.android.bookmarkprovider
adb shell pm uninstall -k --user 0 com.android.chrome
adb shell pm uninstall -k --user 0 com.android.dreams.phototable
adb shell pm uninstall -k --user 0 com.android.hotwordenrollment.okgoogle
adb shell pm uninstall -k --user 0 com.android.hotwordenrollment.xgoogle
adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.waterfall
adb shell pm uninstall -k --user 0 com.android.printspooler
adb shell pm uninstall -k --user 0 com.android.providers.calendar
adb shell pm uninstall -k --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall -k --user 0 com.android.role.notes.enabled
adb shell pm uninstall -k --user 0 com.android.settings.intelligence
adb shell pm uninstall -k --user 0 com.facebook.appmanager
adb shell pm uninstall -k --user 0 com.facebook.katana
adb shell pm uninstall -k --user 0 com.facebook.services
adb shell pm uninstall -k --user 0 com.facebook.system
adb shell pm uninstall -k --user 0 com.google.android.aicore
adb shell pm uninstall -k --user 0 com.google.android.apps.accessibility.voiceaccess
adb shell pm uninstall -k --user 0 com.google.android.apps.aiwallpapers
adb shell pm uninstall -k --user 0 com.google.android.apps.bard
adb shell pm uninstall -k --user 0 com.google.android.apps.docs
adb shell pm uninstall -k --user 0 com.google.android.apps.photos
adb shell pm uninstall -k --user 0 com.google.android.apps.restore
adb shell pm uninstall -k --user 0 com.google.android.apps.tachyon
adb shell pm uninstall -k --user 0 com.google.android.apps.youtube.music
adb shell pm uninstall -k --user 0 com.google.android.feedback
adb shell pm uninstall -k --user 0 com.google.android.gm
adb shell pm uninstall -k --user 0 com.google.android.gms.supervision
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall -k --user 0 com.google.android.healthconnect.controller
adb shell pm uninstall -k --user 0 com.google.android.onetimeinitializer
adb shell pm uninstall -k --user 0 com.google.android.partnersetup
adb shell pm uninstall -k --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall -k --user 0 com.google.android.projection.gearhead
adb shell pm uninstall -k --user 0 com.google.android.safetycenter.resources
adb shell pm uninstall -k --user 0 com.google.android.syncadapters.calendar
adb shell pm uninstall -k --user 0 com.google.android.tts
adb shell pm uninstall -k --user 0 com.google.android.videos
adb shell pm uninstall -k --user 0 com.google.android.youtube
adb shell pm uninstall -k --user 0 com.google.ar.core
adb shell pm uninstall -k --user 0 com.google.audio.hearing.visualization.accessibility.scribe
adb shell pm uninstall -k --user 0 com.google.mainline.telemetry
adb shell pm uninstall -k --user 0 com.linkedin.android
adb shell pm uninstall -k --user 0 com.microsoft.appmanager
adb shell pm uninstall -k --user 0 com.microsoft.office.officehubrow
adb shell pm uninstall -k --user 0 com.microsoft.office.outlook
adb shell pm uninstall -k --user 0 com.microsoft.skydrive
adb shell pm uninstall -k --user 0 com.monotype.android.font.samsungone
adb shell pm uninstall -k --user 0 com.netflix.mediaclient
adb shell pm uninstall -k --user 0 com.osp.app.signin
adb shell pm uninstall -k --user 0 com.samsung.android.aicore
adb shell pm uninstall -k --user 0 com.samsung.android.app.find
adb shell pm uninstall -k --user 0 com.samsung.android.app.interpreter
adb shell pm uninstall -k --user 0 com.samsung.android.app.notes
adb shell pm uninstall -k --user 0 com.samsung.android.app.omcagent
adb shell pm uninstall -k --user 0 com.samsung.android.app.parentalcare
adb shell pm uninstall -k --user 0 com.samsung.android.app.readingglass
adb shell pm uninstall -k --user 0 com.samsung.android.app.sketchbook
adb shell pm uninstall -k --user 0 com.samsung.android.app.spage
adb shell pm uninstall -k --user 0 com.samsung.android.app.tips
adb shell pm uninstall -k --user 0 com.samsung.android.app.updatecenter
adb shell pm uninstall -k --user 0 com.samsung.android.app.watchmanager
adb shell pm uninstall -k --user 0 com.samsung.android.aremoji
adb shell pm uninstall -k --user 0 com.samsung.android.aremojieditor
adb shell pm uninstall -k --user 0 com.samsung.android.authfw
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.agent
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.ondevice.enus
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.ondevice.esus
adb shell pm uninstall -k --user 0 com.samsung.android.bixby.wakeup
adb shell pm uninstall -k --user 0 com.samsung.android.bixbyvision.framework
adb shell pm uninstall -k --user 0 com.samsung.android.carkey
adb shell pm uninstall -k --user 0 com.samsung.android.coldwalletservice
adb shell pm uninstall -k --user 0 com.samsung.android.da.daagent
adb shell pm uninstall -k --user 0 com.samsung.android.dbsc
adb shell pm uninstall -k --user 0 com.samsung.android.dkey
adb shell pm uninstall -k --user 0 com.samsung.android.ese
adb shell pm uninstall -k --user 0 com.samsung.android.fmm
adb shell pm uninstall -k --user 0 com.samsung.android.game.gamehome
adb shell pm uninstall -k --user 0 com.samsung.android.game.gametools
adb shell pm uninstall -k --user 0 com.samsung.android.game.gos
adb shell pm uninstall -k --user 0 com.samsung.android.globalpostprocmgr
adb shell pm uninstall -k --user 0 com.samsung.android.gru
adb shell pm uninstall -k --user 0 com.samsung.android.hwresourceshare.storage
adb shell pm uninstall -k --user 0 com.samsung.android.intellivoiceservice
adb shell pm uninstall -k --user 0 com.samsung.android.ipsgeofence
adb shell pm uninstall -k --user 0 com.samsung.android.kidsinstaller
adb shell pm uninstall -k --user 0 com.samsung.android.knox.zt.framework
adb shell pm uninstall -k --user 0 com.samsung.android.liveeffectservice
adb shell pm uninstall -k --user 0 com.samsung.android.mapsagent
adb shell pm uninstall -k --user 0 com.samsung.android.mdecservice
adb shell pm uninstall -k --user 0 com.samsung.android.mdx
adb shell pm uninstall -k --user 0 com.samsung.android.net.wifi.wifiguider
adb shell pm uninstall -k --user 0 com.samsung.android.nmt.apps.t2t.languagepack.enesus
adb shell pm uninstall -k --user 0 com.samsung.android.offline.languagemodel
adb shell pm uninstall -k --user 0 com.samsung.android.oneconnect
adb shell pm uninstall -k --user 0 com.samsung.android.samsungpass
adb shell pm uninstall -k --user 0 com.samsung.android.samsungpassautofill
adb shell pm uninstall -k --user 0 com.samsung.android.scloud
adb shell pm uninstall -k --user 0 com.samsung.android.scpm
adb shell pm uninstall -k --user 0 com.samsung.android.sdk.ocr
adb shell pm uninstall -k --user 0 com.samsung.android.service.peoplestripe
adb shell pm uninstall -k --user 0 com.samsung.android.service.stplatform
adb shell pm uninstall -k --user 0 com.samsung.android.service.tagservice
adb shell pm uninstall -k --user 0 com.samsung.android.smartmirroring
adb shell pm uninstall -k --user 0 com.samsung.android.smartsuggestions
adb shell pm uninstall -k --user 0 com.samsung.android.smartswitchassistant
adb shell pm uninstall -k --user 0 com.samsung.android.spay
adb shell pm uninstall -k --user 0 com.samsung.android.spayfw
adb shell pm uninstall -k --user 0 com.samsung.android.ssco
adb shell pm uninstall -k --user 0 com.samsung.android.stickercenter
adb shell pm uninstall -k --user 0 com.samsung.android.tvplus
adb shell pm uninstall -k --user 0 com.samsung.android.vision.model
adb shell pm uninstall -k --user 0 com.samsung.android.visionintelligence
adb shell pm uninstall -k --user 0 com.samsung.android.visual.cloudcore
adb shell pm uninstall -k --user 0 com.samsung.android.voc
adb shell pm uninstall -k --user 0 com.samsung.android.vtcamerasettings
adb shell pm uninstall -k --user 0 com.samsung.app.newtrim
adb shell pm uninstall -k --user 0 com.samsung.ecomm
adb shell pm uninstall -k --user 0 com.samsung.petservice
adb shell pm uninstall -k --user 0 com.samsung.sree
adb shell pm uninstall -k --user 0 com.samsung.storyservice
adb shell pm uninstall -k --user 0 com.sec.android.app.billing
adb shell pm uninstall -k --user 0 com.sec.android.app.desktoplauncher
adb shell pm uninstall -k --user 0 com.sec.android.app.kidshome
adb shell pm uninstall -k --user 0 com.sec.android.app.magnifier
adb shell pm uninstall -k --user 0 com.sec.android.app.samsungapps
adb shell pm uninstall -k --user 0 com.sec.android.app.sbrowser
adb shell pm uninstall -k --user 0 com.sec.android.app.setupwizard
adb shell pm uninstall -k --user 0 com.sec.android.app.shealth
adb shell pm uninstall -k --user 0 com.sec.android.app.ve.vebgm
adb shell pm uninstall -k --user 0 com.sec.android.app.vepreload
adb shell pm uninstall -k --user 0 com.sec.android.app.voicenote
adb shell pm uninstall -k --user 0 com.sec.android.autodoodle.service
adb shell pm uninstall -k --user 0 com.sec.android.desktopmode.uiservice
adb shell pm uninstall -k --user 0 com.sec.android.dexsystemui
adb shell pm uninstall -k --user 0 com.sec.android.easyMover
adb shell pm uninstall -k --user 0 com.sec.android.easyonehand
adb shell pm uninstall -k --user 0 com.sec.android.mimage.avatarstickers
adb shell pm uninstall -k --user 0 com.sec.android.mimage.photoretouching
adb shell pm uninstall -k --user 0 com.sec.location.nsflp2
adb shell pm uninstall -k --user 0 com.sec.penup
adb shell pm uninstall -k --user 0 com.spotify.music
echo Killing adb server
adb kill-server
echo Press any key to exit terminal.
pause
